site_name: Tejashri Kelhe 
site_description: Personal website and portfolio

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - content.code.copy
    - header.autohide
  palette:
  - scheme: default
    primary: dark blue
    accent: teal
  extra_css:
  - assets/custom.css


nav:
  - Home: index.md
  - About: about.md
  - Experience: experience.md
  - Patent: patent.md
  - Research: research.md
  - Projects: projects.md
  - Skills: skills.md
  - Education: education.md
  - Contact: contact.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - attr_list




